version: '3.8'
services:
  db_postgres:
    container_name: db_postgres
    image: postgres:15
#    restart: always
    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data      

  app:
    container_name: app-micros
    build: .
    depends_on:
      - db_postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:5432/db_postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
volumes:
  pgdata: